proxy: Initialize M2Crypto threading module
We have this a random unexplained error during automation:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_common/web.py", line 64, in __call__
    resp = self.dispatch(request)
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_common/web.py", line 91, in dispatch
    return method(*match.groups())
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_proxy/tickets.py", line 31, in put
    auth.add_signed_ticket(self.request.body)
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_proxy/auth.py", line 184, in add_signed_ticket
    payload = _decode_ovirt_ticket(data)
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_proxy/auth.py", line 231, in _decode_ovirt_ticket
    return decoder.decode(data)
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_proxy/ticket.py", line 94, in decode
    self._verifyCertificate(self._ca, x509)
  File "/usr/lib/python2.7/site-packages/ovirt_imageio_proxy/ticket.py", line 70, in _verifyCertificate
    x509.get_not_before().get_datetime().replace(tzinfo=None) <=
  File "/usr/lib64/python2.7/site-packages/M2Crypto/ASN1.py", line 181, in get_datetime
    tm = list(time.strptime(rest, "%d %H:%M:%S %Y"))[:6]
AttributeError: _strptime_time

M2Crypto requires explicit initialization when used in multi-threaded
program. Not doing this caused segfaults in vdsm, see:
https://bugzilla.redhat.com/482420

I don't know if this change will fix the proxy bug, but I'm sure
adding this initialization is correct.

Initializing M2Crypto in the main module, before we run any other code
is the safest place to initialize it, ensuring that it will be
initialized when we actualy use it when adding tickets.

Change-Id: I1a92fe9212b186a1bd4b9dd5f37ea70e9f78ea72
Bug-Url: https://bugzilla.redhat.com/1576500
Signed-off-by: Nir Soffer <nsoffer@redhat.com>