tests: Skip IPv6 link local addresses
Running the tests locally, test_server_bind_addr_from_hostname() fails
with this error:

    OSError: [Errno 22] Invalid argument

Trying the same code in the shell shows that getaddrinfo() returns:

>>> socket.getaddrinfo(socket.gethostname(), 0, type=socket.SOCK_STREAM)[0]
(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::b557:c49c:3ecb:df3b', 0, 0, 4))

('fe80::b557:c49c:3ecb:df3b', 0, 0, 4) is a link local address[1]
(address, port, flow, scope id).

When binding this address we must use the complete tuple:

>>> s.bind(('fe80::b557:c49c:3ecb:df3b', 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument

>>> s.bind(('fe80::b557:c49c:3ecb:df3b', 0, 0, 4))

We can fix the demo_server helper and http.Server to accept IPv6 4 tuple
address so we can listen to link local addresses. But I don't think this
is useful for a server, since link local address are local.

Filter link local addresses in this test, and use parameters to avoid
failing the entire test when one address is problematic, and improve
test output.

Here is log from the tests with this fix:

test/http_test.py::test_server_bind_addr_from_hostname[192.168.1.167] PASSED
test/http_test.py::test_server_bind_addr_from_hostname[192.168.122.1] PASSED
test/http_test.py::test_server_bind_addr_from_hostname[192.168.1.163] PASSED
test/http_test.py::test_server_bind_addr_from_hostname[10.35.1.2] PASSED

[1] https://en.wikipedia.org/wiki/Link-local_address

Change-Id: Ie19d55ecf510f045be1edfa5615963727e9f9ed4
Signed-off-by: Nir Soffer <nsoffer@redhat.com>