tests: Add failing test for passing errors
The http backend does convert all server errors to RuntimeError. For
example, getting missing ticket raises:

    RuntimeError: Error OPTIONS: b'You are not allowed to access this
    resource: No such ticket 4acabaa9-fe37-49ad-bca3-405d60094146'

Which returns "500 Internal server error" to the proxy client. This
makes it harder to debug application using the proxy.

Add a failing test reproducing this issue.

Change-Id: Ibce83df32af8c7508788f63c2c46ce1951039f0a
Signed-off-by: Nir Soffer <nsoffer@redhat.com>