tox: Fix bench targets
Turns out that tox conditional settings do not cope well with wrapped
command lines. tox -e bench fails now with:

    ERROR: InvocationError for command could not find executable 'cov=ovirt_imageio_daemon'

Using single line per command is ugly but solves this issue.

Change-Id: Ia7a184320fae7d32b52c61a74f062e31c1256de4
Signed-off-by: Nir Soffer <nsoffer@redhat.com>