http: Filter IPv6 link local addresses
The same issue we had in the tests is also happens in the server if you
try to configure:

[remote]
host = my.host.name

Starting the server fails with:

$ ./ovirt-imageio -c test
2020-07-22 23:42:36,359 INFO    (MainThread) [server] Starting (pid=479331, version=2.0.10)
2020-07-22 23:42:36,359 DEBUG   (MainThread) [services] Creating remote.service on port 54322
2020-07-22 23:42:36,395 DEBUG   (MainThread) [http] Prefer IPv4: False
2020-07-22 23:42:36,395 DEBUG   (MainThread) [http] Available network interfaces:
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::b557:c49c:3ecb:df3b', 54322, 0, 4)), ...
2020-07-22 23:42:36,395 DEBUG   (MainThread) [http] Creating server socket with
family=AddressFamily.AF_INET6 and type=SocketKind.SOCK_STREAM
2020-07-22 23:42:36,422 ERROR   (MainThread) [server] Server failed
Traceback (most recent call last):
  File "/home/nsoffer/src/ovirt-imageio/daemon/ovirt_imageio/_internal/server.py", line 46, in main
    server = Server(cfg)
  File "/home/nsoffer/src/ovirt-imageio/daemon/ovirt_imageio/_internal/server.py", line 110, in __init__
    self.remote_service = services.RemoteService(self.config, self.auth)
  File "/home/nsoffer/src/ovirt-imageio/daemon/ovirt_imageio/_internal/services.py", line 74, in __init__
    self._server = http.Server((config.remote.host, port), http.Connection)
  File "/home/nsoffer/src/ovirt-imageio/daemon/ovirt_imageio/_internal/http.py", line 95, in __init__
    self.server_bind()
  File "/home/nsoffer/src/ovirt-imageio/daemon/ovirt_imageio/_internal/http.py", line 140, in server_bind
    super().server_bind()
  File "/usr/lib64/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 22] Invalid argument

Add http.find_addresses() helper for getting available addresses and
filtering unwanted addresses. This is also a good place for replacing
host="" with host=0, since it is needed only for socket.getaddrinfo().
The tests use the same helper to look up available addresses for
testing.

Starting the server succeeds now using IPv4 address since this host does
not have an IPv6 address:

$ ./ovirt-imageio -c test
2020-07-22 23:40:08,336 INFO    (MainThread) [server] Starting (pid=479042, version=2.0.10)
2020-07-22 23:40:08,336 DEBUG   (MainThread) [services] Creating remote.service on port 54322
2020-07-22 23:40:08,366 DEBUG   (MainThread) [http] Prefer IPv4: False
2020-07-22 23:40:08,366 DEBUG   (MainThread) [http] Available network interfaces:
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.1.167', 54322)),
...
2020-07-22 23:40:08,366 DEBUG   (MainThread) [http] Creating server socket with
family=AddressFamily.AF_INET and type=SocketKind.SOCK_STREAM
2020-07-22 23:40:08,479 DEBUG   (MainThread) [services] Securing server (cafile=test/pki/ca.pem,
certfile=test/pki/cert.pem, keyfile=test/pki/key.pem)
2020-07-22 23:40:08,482 INFO    (MainThread) [services] remote.service listening on ('192.168.1.167', 54322)
...

Change-Id: I598171acf8ad483a1672a34c347d69f214d03f57
Signed-off-by: Nir Soffer <nsoffer@redhat.com>