wsgi: Fix error handling during iteration
Turns out that error handling during iteration is completely broken,
calling ServerHandler.close() 3! times.

This breaks with this error:

Exception happened during processing of request from ('172.17.0.1', 43398)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/app/ovirt_imageio_daemon/wsgi.py", line 117, in handle
    self.handle_one_request()
  File "/app/ovirt_imageio_daemon/wsgi.py", line 98, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/app/ovirt_imageio_daemon/wsgi.py", line 159, in close
    if status >= 400 and self.environ["CONTENT_LENGTH"]:
TypeError: 'NoneType' object has no attribute '__getitem__'

Adding logs show that close() was called 3 times:
1. Once with status='200 OK' and original environ dict
2. Second time with status='500 Internal Server' and environ=None
3. Finally, with status=None

Fix the issue by overriding more code from wsgiref.handlers.BaseHandler,
ensuring that close() is called exactly once.

Also improve logging by using our logger and adding more debug messages.

Change-Id: Idc0559b75b7a57b1c766d868d96719f89c84cd85
Signed-off-by: Nir Soffer <nsoffer@redhat.com>