server: Fail fast with invalid config directory
If a user runs ovirt-imageio or ovirt-imageioctl with invalid
configuration directory, we silently ignored the directory since it has
no configuration files, and failed later when with a confusing error
message.

Change server.load_config() to validate that the configuration directory
contains at least one configuration file. This will also fail if the
default configuration directory (/etc/ovirt-imageio) becomes broken.

Failing fast will help users to fix the issue quickly.

Example failure with this change:

    $ ./ovirt-imageio -c test/conf
    Server failed
    Traceback (most recent call last):
      File "/home/nsoffer/src/ovirt-imageio/ovirt_imageio/_internal/server.py", line 38, in main
        cfg = load_config(args.conf_dir)
      File "/home/nsoffer/src/ovirt-imageio/ovirt_imageio/_internal/server.py", line 93, in load_config
        raise ValueError(f"Cound not find {pattern}")
    ValueError: Cound not find test/conf/conf.d/*.conf

The change removes the server.find_config(), since we can test the
behavior using server.load_config(), add tests for various failure
cases, and improve documentation in server.load_config().

Fixes #33

Signed-off-by: Nir Soffer <nsoffer@redhat.com>