nbd: readinto - read exact size of data
backends/nbd -> readinto:
When the buffer size is larger than the remaining data to read,
we fail on nbd server[*] as we try to read beyond available size.
Hence, the suggested patch ensures that exactly the remaining data
size is read.

[*] [http] Request aborted after starting response
Traceback (most recent call last):
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/http.py", line 671, in __call__
   self.dispatch(req, resp)
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/http.py", line 716, in dispatch
   return method(req, resp, *match.groups())
 File "/usr/lib/python2.7/site-packages/ovirt_imageio_daemon/images.py", line 123, in get
   ticket.run(op)
 File "/usr/lib/python2.7/site-packages/ovirt_imageio_daemon/auth.py", line 116, in run
   operation.run()
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/ops.py", line 62, in run
self._run()
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/ops.py", line 91, in _run
   self._send_chunk(buf)
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/ops.py", line 102, in _send_chunk
   count = self._src.readinto(buf)
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/backends/nbd.py", line 73, in readinto
   data = self._client.read(self._position, len(buf))
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/nbd.py", line 298, in read
   self._receive_simple_reply(handle)
 File "/usr/lib64/python2.7/site-packages/ovirt_imageio_common/nbd.py", line 659, in _receive_simple_reply
   raise Error("Error {}: {}".format(error, strerror(error)))
Error: Error 22: Unknown error

Change-Id: I44925bd695111133eaee5b74cd6b5541a8e33bda
Signed-off-by: Daniel Erez <derez@redhat.com>