nbd: Ensure memoryview release underlying buffer
Without calling release() or using a memoryview as a context manager,
explicitly closing the underlying buffer as we do for the operations
aligned buffer will fail with:

    BufferError: cannot close exported pointers exist

Fix memoryview usage in the nbd client they may interact with operation
buffer, so we can pass the operation buffer down to the client, avoiding
memory copies.

Change-Id: Ibe957cc724f71433a9a2460511bc1d3cf5e916dc
Signed-off-by: Nir Soffer <nsoffer@redhat.com>