http: Increase listen backlog to 40
Both TCP and unix socket based servers inherited the listen backlog from
python socketserver.TCPServer. The default value (5) was never a
problem, but new automated tests using 16 concurrent connections started
to fail randomly recently with:

ERR: Traceback (most recent call last):
  ...
  File "ovirt_imageio/_internal/backends/http.py", line 392, in _create_unix_connection
    con.connect()
  File "ovirt_imageio/_internal/backends/http.py", line 627, in connect
    self.sock.connect(self.path)
BlockingIOError: [Errno 11] Resource temporarily unavailable

Increase the backlog to 40. We recommend to do up to 10 image transfers
per host. Doing more will work, but if someone will try to start 60
connections at the same time they will likely experience the same error,
which is good sign that they are overloading the system.

Bug-Url: https://bugzilla.redhat.com/2066113
Signed-off-by: Nir Soffer <nsoffer@redhat.com>