configloader: Port to python 3
ConfigParser.get() returns bytes in python 2 (e.g. "\xd7\x90") and
unicode in python 3 (e.g. u"\u05d0"). Change configloader to always
decode bytes values to unicode to get consistent behaviour in all python
version.

Since we use the type of the default values from the config module,
change the loader to support only unicode in python 2, and str in python
3 (six.text_type).

When starting a service with empty abstract socket we update the config
with the random socket selected by the kernel (e.g. "\0000378"), so we
must decode the socket address.

Loading config object with bytes default value ("value" in python2, or
b"value" in python 3) raises ValueError:

    ValueError: Unsupported default value type for 'section.value': <class 'bytes'>

Change-Id: I866b25171482f7178e55ca4382937d9b077ea432
Signed-off-by: Nir Soffer <nsoffer@redhat.com>