daemon: Fail OPTIONS request if ticket expired
We want to allow a client to extend a ticket by issuing OPTIONS request.
However a client should not be able to extend a ticket after it was
expired. To fix this we need to use tickets.authorize() to get a ticket.
This method will fail if the ticket has expired.

Here is an example of failed upload when a ticket has expired:

$ ./upload /var/tmp/fedora-27.img https://host:54322/images/test
Traceback (most recent call last):
  File "./upload", line 263, in <module>
    server_options = options(con, url.path)
  File "./upload", line 240, in options
    raise RuntimeError("options %s failed: %s" % (path, body))
RuntimeError: options /images/test failed: {"explanation": "Access was
denied to this resource.", "code": 403, "detail": "Ticket u'test' expired",
"title": "Forbidden"}

Although this does change OPTIONS behavior, it cannot break a client,
since even before this change, any useful request (e.g. PUT, GET) would
fail if a ticket has expired.

Change-Id: Ia92d42bab8eb6ab56896086a7ac11c4a15bb49d7
https://bugzilla.redhat.com/1619019
Signed-off-by: Nir Soffer <nsoffer@redhat.com>