automation: Require tox 3.14
This version fixed issue with more_itertools breaking all python
projects lately:

    Traceback (most recent call last):
      File "/usr/bin/tox", line 7, in <module>
        from tox import cmdline
      File "/usr/lib/python2.7/site-packages/tox/__init__.py", line 9, in <module>
        import pluggy
      File "/usr/lib/python2.7/site-packages/pluggy/__init__.py", line 16, in <module>
        from .manager import PluginManager, PluginValidationError
      File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 6, in <module>
        import importlib_metadata
      File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
        import zipp
      File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
        import more_itertools
      File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
        from more_itertools.more import *  # noqa
      File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 340
        def _collate(*iterables, key=lambda a: a, reverse=False):
                                   ^
    SyntaxError: invalid syntax

Change-Id: I23e4f35637a21d823a97ab83f1bc302c5317d301
Signed-off-by: Nir Soffer <nsoffer@redhat.com>